[workspace]
members = [
    "examples",
    "generative_design",
    "guide/book_tests",
    "nannou",
    "nannou_audio",
    "nannou_conrod",
    "nannou_core",
    "nannou_isf",
    "nannou_laser",
    "nannou_mesh",
    "nannou_new",
    "nannou_osc",
    "nannou_package",
    "nannou_timeline",
    "nannou_wgpu",
    "nature_of_code",
    "scripts/run_all_examples",
    "scripts/set_version",
]

# Required for wgpu v0.10 feature resolution.
resolver = "2"

[patch.crates-io]
conrod_core = { git = "https://github.com/pistondevelopers/conrod", branch = "master" }
conrod_wgpu = { git = "https://github.com/pistondevelopers/conrod", branch = "master" }
conrod_winit = { git = "https://github.com/pistondevelopers/conrod", branch = "master" }
